# Generated by Django 4.1.5 on 2023-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('year', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Год')),
                ('salary', models.IntegerField(verbose_name='Зарплата в рублях')),
                ('count', models.IntegerField(verbose_name='Количество вакансий')),
                ('chosen_salary', models.IntegerField(verbose_name='Зарплата в рублях для выбранной профессии')),
                ('chosen_count', models.IntegerField(verbose_name='Количество вакансий для выбранной профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('area_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Город')),
                ('salary', models.IntegerField(verbose_name='Зарплата в рублях')),
                ('fraction', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Доля вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
        ),
    ]
