# Generated by Django 4.1.5 on 2023-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rank',
            field=models.SmallIntegerField(default=None, verbose_name='№'),
        ),
    ]
