# Generated by Django 4.1.5 on 2023-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_skill_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
