# Generated by Django 4.1.5 on 2023-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(default='RUR', max_length=3),
        ),
    ]
