# Generated by Django 4.1.5 on 2023-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vacancy_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='href',
            field=models.CharField(default='https://www.hh.ru/', max_length=200),
        ),
    ]
